### ISSUE TITLE
对文档“2017nscscc.pdf”中裁剪linux内核去除tne指令的疑问

### ISSUE THREAD

**Issue by NoWarnings** [z4yx/NaiveMIPS-HDL#1]
[该文档](https://github.com/z4yx/NaiveMIPS-HDL/blob/brd-NSCSCC/documentation/2017nscscc.pdf)第42页关于去除tne指令的说明：

>  break和 tne指令去除：MIPS架构自己实现了BUG和BUG_ON（在 arch/mips/include/asm/bug.h 文件中），用到了 Trap 机制，即 break 和 tne 指令，Trap 机制硬件上没有实现。因此直接注释掉指令，使用 generic 的 BUG() 实现。 

 请问直接注释掉指令是指什么？

**Comment by z4yx** [comment]
见代码 [bug.h](https://github.com/z4yx/linux-kernel/blob/naivemips/arch/mips/include/asm/bug.h)
用 `#if 0` 注释了整个宏定义，从而使用 `asm-generic/bug.h` 中的宏定义
